smartlocker/models/lockers.py
import mongoengine as me
import datetime

from . import User

class Locker(me.Document):
    name = me.StringField(required=True,default='-')
    status_opened = me.BooleanField(default=False)
    renter = me.ReferenceField(User, dbref=True)
    size = me.StringField(default='S')
    availability = me.BooleanField(default=True)
    started_date = me.DateTimeField(required=True,
                                    default=datetime.datetime.now)
    expired_date = me.DateTimeField(required=True,
                                    default=datetime.datetime.now)

    meta = {'collection': 'lockers'}

smartlocker/forms/lockers.py
from flask_wtf import FlaskForm
from wtforms import Form
from wtforms import fields
from wtforms import validators

class AddLockersForm(FlaskForm):
    name = fields.TextField('Name',
                    validators=[validators.InputRequired(), 
                    validators.Length(min=2)])
    size = fields.TextField('Size', 
                    validators=[validators.InputRequired()])

class ReserveLockerForm(FlaskForm):
    hour = fields.SelectField('Hour', coerce=int)

smartlocker/views/dashboard.py
from flask import (Blueprint, 
                    request,
                    redirect,
                    url_for,
                    render_template)
from flask_login import (current_user,
                        login_required)
from .. import models
from .. import acl
from .. import mqtt
from smartlocker.forms import (AddLockersForm, 
                              ReserveLockerForm)
import datetime

module = Blueprint('dashboard', __name__, url_prefix='/dashboard')

@module.route('/', methods=['GET', 'POST'])
@login_required
def index():
    lockers=models.Locker.objects(renter=current_user._get_current_object())
    curr_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return render_template('dashboard/index.html',
                            user=current_user,
                            lockers=lockers,
                            curr_time=curr_time)


@module.route('/lockers')
@login_required
def lockers():
    lockers = models.Locker.objects() 
    return render_template('dashboard/lockers.html',
                            user=current_user,
                            lockers=lockers)

@module.route('/addlockers', methods=['GET', 'POST'])
@login_required
@acl.allows.requires(acl.is_admin)
def addlocker():
    form = AddLockersForm()
    if not form.validate_on_submit():
        return render_template('/dashboard/addlockers.html', 
                                form=form,
                                user=current_user)
    data = form.data.copy()
    data.pop('csrf_token')
    locker = models.Locker(**data).save()

    return redirect(url_for('dashboard.lockers'))

@module.route('/<locker_id>/reserve', methods=['GET', 'POST'])
@login_required
def reserve(locker_id):
    locker = models.Locker.objects.get(id=locker_id)
    # print('got', datetime.datetime.now())
    if locker.availability == False:
        return redirect(url_for('dashboard.lockers'))
    hours = [1, 3, 6, 9, 12]
    form = ReserveLockerForm()
    form.hour.choices = [(h, str(h)) for h in hours]
    if not form.validate_on_submit():
        return render_template('/dashboard/reservation.html',
                                user=current_user,
                                form=form)
    exp=datetime.datetime.now()
    if form.hour.data in [1,3,6,9,12]:
        # print('dalta')
        exp=datetime.timedelta(hours=form.hour.data)
        locker.update(started_date=datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                expired_date=(datetime.datetime.now()+exp).strftime("%Y-%m-%d %H:%M:%S"),
                 renter=current_user._get_current_object(),
                 availability=False)
        locker.save()
    return redirect(url_for('dashboard.lockers'))

@module.route('openlocker/<locker_id>', methods=['GET', 'POST'])
@login_required
def openlocker(locker_id):
    locker = models.Locker.objects.get(id=locker_id)
    if locker.availability == True:
        return redirect(url_for('dashboard.index'))
    else:
        mqtt.openlocker.openLocker(locker.name)
    return 'open'

smartlocker/views/lockers.py
from flask import (Blueprint, 
                    request,
                    redirect,
                    url_for,
                    render_template,
                    jsonify)
from flask_login import (current_user,
                        login_required)
from .. import models
from .. import acl
from .. import mqtt
from smartlocker.forms import (AddLockersForm, 
                              ReserveLockerForm)
import datetime

module = Blueprint('lockers', __name__, url_prefix='/lockers')


@module.route('/<locker_id>/status', methods=['GET', 'POST'])
@login_required
def status(locker_id):
    locker=models.Locker.objects.get(id=locker_id,
                                      renter=current_user._get_current_object())
    curr_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return jsonify(dict(id=str(locker.id),
                        opened_status=locker.status_opened,
                        ))

smartlocker/templates/dashboard/addlockers.html
{% extends "base/base_layout.html" %}
{% block main %}
<div class="row">
	<h4>Add Locker</h4>
	<form action="{{request.path}}" method="POST">
	{{ form.csrf_token }}
	<div class="row">
	<div>
	<div class="input-field col s12">
	{{ form.name }}
	{{ form.name.label }}
	</div>

	<div class="input-field col s12">
	{{ form.size }}
	{{ form.size.label }}
	</div>
	</div>
	</div>
	<button type="submit" class ="indigo darken-1 waves-effect waves-light btn">ADD</button>	
	</form>
</div>
{% endblock %}

smartlocker/templates/dashboard/index.html
{% extends "base/base_layout.html" %}
{% block main %}
<h3>My Locker</h3>
<div class="row">
{% for locker in lockers %}
<div class="col s12 m6">
<div class="card-panel grey darken-4 white-text">
	<p id="{{ locker.id }}" class="left"><i class="medium material-icons">brightness_1</i></p>
<p class="white-text right"><i class="tiny material-icons">access_time</i> EXP:{{ locker.expired_date }} </p>
<h4><i class="medium material-icons center">dns</i>{{ locker.name }}</h4>

<a href="#" onclick="openLocker('{{ locker.id }}')" class="waves-effect waves-light btn light-blue darken-4"><i class="material-icons left">lock_open</i>OPEN</a>

</div>
</div>
{% endfor %}

</div>
<script type="text/javascript">
{% for locker in lockers %}
//var curr_sta = 'True';
//if curr_sta != '{{ locker.status_opened }}' {
var myVar = setInterval(loadDoc, 1000, "{{ locker.id }}"); 
//	var curr_sta = '{{ locker.status_opened }}';
//}
{% endfor %}
</script>
{% endblock %}

smartlocker/templates/dashboard/lockers.html
{% extends "base/base_layout.html" %}
{% block main %}
<div class="container">
	<h4>Select Locker to reservation</h4>
	<br>
	{% if user.roles == 'admin' %}
	<a href="addlockers" class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">add</i></a>
	{% endif %}
	<div class="row">
	 <table class="highlight">
        <thead>
          <tr>
              <th>Locker</th>
              <th>Size</th>
	      <th>Status</th>
		<th>Select</th>
	{% if user.roles == 'admin' %}
	      <th>Renter</th>
	      <th>EXP</th>
	{% endif %}
          </tr>
        </thead>
	{% for locker in lockers %}
        <tbody>
          <tr>
		  <td>{{ locker.name }}</td>
		  <td>{{ locker.size }}</td>
		  {% if locker.availability == true %}
		  <td>
		  <div class="chip green darken-2 white-text">Availability</div>
		  </td>
		  <td>
		  <a href="{{ url_for('dashboard.reserve', locker_id=locker.id) }}" class="waves-effect waves-light btn indigo darken-4">reserve</a>
		  </td>
		{% else %}
		  <td>
		  <div class="chip red darken-2 white-text">Reserved</div>
		  </td>

		  <td>
		  <a class="waves-effect waves-light btn disabled">reserve</a>
		  </td>
		  {% endif %}
	{% if user.roles == 'admin' %}
	<td>{{ locker.renter.username }}</td>
	<td>{{ locker.expired_date }}</td>
	{% endif %}
	  </tr>
	  {% endfor %}
        </tbody>
      </table>
	</div>
</div>

{% endblock %}

smartlocker/templates/dashboard/reservation.html
{% extends "base/base_layout.html" %}
{% block main %}
<br>
<div class="row">
<h4>Select Hour to reservation</h4>
      <table class="striped col s12 l6">
        <thead>
          <tr>
              <th>Hour</th>
              <th>Price (points)</th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td>1</td>
            <td>500</td>
          </tr>
          <tr>
            <td>3</td>
            <td>1500</td>
          </tr>
          <tr>
            <td>6</td>
            <td>5000</td>
          </tr>
          <tr>
            <td>9</td>
            <td>7000</td>
          </tr>
          <tr>
            <td>12</td>
            <td>10,000</td>
          </tr>
        </tbody>
      </table>
      <br>
<form action="{{request.path}}" method="POST">
{{ form.csrf_token }}
  <div class="input-field col s6">

{{ form.hour }}
{{ form.hour.label }}
</div>
<button type="submit" class ="indigo darken-1 waves-effect waves-light btn">RESERVE</button>

</form>
</div>
{% endblock %}